### ISSUE TITLE
Using unexported symbols results in compilation errors.

### ISSUE THREAD

**Issue by Ferada** [mfiano/parsley#1]
`fast-io`'s `input-buffer-stream` and `input-buffer-vector` are not exported, using them results in (continuable) compilation errors on at least CCL:

```
Reader error: No external symbol named "INPUT-BUFFER-VECTOR" in package #<Package "FAST-IO"> .
```

**Comment by mfiano** [comment]
They are exported, on line 13 of the package definition, and I cannot reproduce the problem on CCL.

**Comment by Ferada** [comment]
Indeed, I must've made a mistake when fetching updates for `fast-io`. Sorry for the noise.
